name: CI

on:
  pull_request:
    branches:
      - main

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Run tests
      shell: bash
      run: cargo test

    - name: Check code
      shell: bash
      run: |
        cargo check
        cargo clippy -- -D warnings